services:
    Localinks\DependentAutoCompleteBundle\Form\Extension\DependentAutoCompleteTypeExtension:
        tags:
            - { name: form.type_extension, alias: localinks_dependent_auto_complete_type, extended_type: Sonata\AdminBundle\Form\Type\ModelAutocompleteType }

    localinks.admin.controller.admin:
        class: Localinks\DependentAutoCompleteBundle\Controller\AdminController
        arguments: ["@twig", "@sonata.admin.pool", "@sonata.admin.helper", "@validator"]
